#!/usr/bin/env python3
"""
Emit SQL to migrate Pimcore -> OpenDXP database remnants.

The toolkit stays DB-driver-free on purpose: this command prints SQL to stdout.
Review it, then pipe it into your database yourself (inside the db container),
so nothing is changed implicitly.

What it covers:
  * settings_store: BUNDLE_INSTALLED__Pimcore...  -> ...OpenDxp...
  * settings_store: scope `pimcore` / `pimcore_*` -> `opendxp` / `opendxp_*`
  * (optional) migration_versions: drop the old Pimcore CoreBundle migration log

Usage:
  opendxp_migrate_db.py emit-sql [--with-migration-cleanup]
                                 [--migration-like 'Pimcore%CoreBundle%Migrations%']

Apply (example, MariaDB/MySQL in Docker):
  python3 opendxp_migrate_db.py emit-sql > migrate.sql
  docker exec -i <db_container> mysql -upimcore -ppimcore pimcore < migrate.sql

Note on `migration_versions`:
  Deleting the old log can make OpenDXP consider its (renamed) migrations as
  "not yet run". Only enable --with-migration-cleanup once you have decided how to
  baseline the OpenDXP migrations (see OpenDXP Upgrade Notes). For just reaching
  the admin UI it is NOT required.
"""

from __future__ import annotations

import argparse
import sys

SETTINGS_STORE_SQL = """\
-- ---------------------------------------------------------------------------
-- settings_store: bundle install markers (Pimcore... -> OpenDxp...)
-- REPLACE() handles both the namespace prefix and the class-name suffix.
-- ---------------------------------------------------------------------------
SELECT CONCAT('BUNDLE_INSTALLED rows before: ', COUNT(*))
  FROM settings_store WHERE id LIKE 'BUNDLE_INSTALLED__Pimcore%';

UPDATE settings_store
   SET id = REPLACE(id, 'Pimcore', 'OpenDxp')
 WHERE id LIKE 'BUNDLE_INSTALLED__Pimcore%';

-- ---------------------------------------------------------------------------
-- settings_store: scopes (pimcore / pimcore_* -> opendxp / opendxp_*)
-- e.g. pimcore_system_settings, pimcore_image_thumbnails, pimcore_staticroutes ...
-- ---------------------------------------------------------------------------
SELECT CONCAT('pimcore* scopes before: ', COUNT(DISTINCT scope))
  FROM settings_store WHERE scope LIKE 'pimcore%';

UPDATE settings_store
   SET scope = REPLACE(scope, 'pimcore', 'opendxp')
 WHERE scope LIKE 'pimcore%';

SELECT CONCAT('pimcore* scopes after:  ', COUNT(DISTINCT scope))
  FROM settings_store WHERE scope LIKE 'pimcore%';
"""

MIGRATION_CLEANUP_SQL = """\
-- ---------------------------------------------------------------------------
-- migration_versions: drop the old Pimcore CoreBundle migration log.
-- Wildcards (%) are used instead of literal backslashes to avoid MySQL LIKE
-- escaping. Review the SELECT output before trusting the DELETE.
-- ---------------------------------------------------------------------------
SELECT CONCAT('migration rows to delete: ', COUNT(*))
  FROM migration_versions WHERE version LIKE '{like}';

DELETE FROM migration_versions WHERE version LIKE '{like}';
"""


def build_sql(with_migration_cleanup: bool, migration_like: str) -> str:
    parts = [
        "-- Generated by opendxp_migrate_db.py - REVIEW before applying.",
        "-- Make a database backup first.",
        "",
        "START TRANSACTION;",
        "",
        SETTINGS_STORE_SQL,
    ]
    if with_migration_cleanup:
        parts.append(MIGRATION_CLEANUP_SQL.format(like=migration_like))
    parts.append("COMMIT;")
    parts.append("")
    return "\n".join(parts)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Emit SQL for Pimcore -> OpenDXP database remnants (DB-driver-free).",
    )
    sub = parser.add_subparsers(dest="command", required=True)

    emit = sub.add_parser("emit-sql", help="Print migration SQL to stdout.")
    emit.add_argument(
        "--with-migration-cleanup",
        action="store_true",
        help="Also emit the migration_versions cleanup DELETE (opt-in).",
    )
    emit.add_argument(
        "--migration-like",
        default="Pimcore%CoreBundle%Migrations%",
        help="LIKE pattern for migration_versions cleanup "
             "(default: 'Pimcore%%CoreBundle%%Migrations%%').",
    )

    args = parser.parse_args()
    if args.command == "emit-sql":
        sys.stdout.write(build_sql(args.with_migration_cleanup, args.migration_like))
        return 0
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
